---
version: '3'
services:
  proxy:
    image: nginx:1.18
    restart: always
    ports:
      - 3000:443
    volumes:
      - ./etc/nginx:/etc/nginx:ro

  grafana:
    image: grafana/grafana:7.1.5
    restart: always
    volumes:
      - ./etc/grafana:/etc/grafana/
      - ./var/lib/grafana:/var/lib/grafana/
      - ./var/log/grafana:/var/log/grafana/
    environment:
      - GF_INSTALL_PLUGINS=sileht-gnocchi-datasource
      - GF_ALLOW_LOADING_UNSIGNED_PLUGINS=sileht-gnocchi-datasource
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.ucsd.edu:25
      - GF_SMTP_FROM_ADDRESS=no_reply@analytic02.sdsc.edu